### ISSUE TITLE
see the parent entity

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#32]
In the entity linked to another entity, see the list of the parent entities

**Comment by victor-xm** [comment]
Expected result description: 
Configuration of the child->parent link should look like this:
      links:
          - key: LEADRESP (same link key as for parent->child link)
            builderType: PARENT (means it can be shown, but not changed through the form)
            builderType: PARENT_SEARCH (means it is shown and link can be deleted or added through the form)
            name: "Parent Entities"
            icon: account_balance_wallet
            typeKey: LEAD (parent entity name, if necessary to specify)

All visualization should be similar to the normal parent->child form.

If the chilf->parent link is not specified, it's not shown on the screen.

**Comment by sergeysenja1992** [comment]
Links in specification it's not only for UI, it's a data model description too. 
If you add item to links, it mean entity refers to another entity by this link. 
builderType it's bad parameter for link direction
Entity already has a source link. Maybe better add just UI property to display source link?

**Comment by ishkurko** [comment]
I agree that the specification should be aimed at the data model description and not the UI. Therefore, I suggest to use the current data model and adding the visualization in the form of a table, with all referring entities.
An example of such a visualization could be found on the image below.
<img width="1150" alt="xm2-referring-entitties-concept-1" src="https://user-images.githubusercontent.com/7899393/34693407-0e3bf016-f4cc-11e7-86bc-87f58e85e0c9.png">

Entity specification like:
```
    - key: FAMILY
      name: { en: "Customer Families"}
      ...
    - key: ACCOUNT.CUSTOMER
      name: { en: "Customers"}
      ...
      links:
        - key: CUSTOMER.FAMILY
          builderType: SEARCH
          name: { en: "Customer Family"}
          icon: language
          typeKey: FAMILY
```
will be interpreted in the UI for the `ACCOUNT.CUSTOMER` with the possibility to manage links `CUSTOMER.FAMILY` and for the `FAMILY` just Referring entities table.
