### ISSUE TITLE
Entity Data field and attachment content encryption

### ISSUE THREAD

**Issue by ishkurko** [xm-online/xm-online#42]
## Why is encryption?
Encryption is the process of encoding information in a way that prevents unauthorized parties from being able to read it.

Encryption strength is most commonly equated to key length (bits) and the encryption algorithm used. The simplest way to defeat encryption is to try all the possible keys. This is known as a brute-force attack, but longer keys have made this approach ineffective.

Attackers do not typically try to reverse-engineer the algorithm or brute force the key.

This feature is in demand because of GDPR rules.

## What is the target?
Encrypted personal content –  entity Data fields and attachments content encryption.

## Configuration
On the level of entity specification 
```
    - key: ACCOUNT.USER
      name: { en: "User", ru: "Пользователь" }
      isApp: true
      isAbstract: false
      dataEncryption: AES
      attachments:
          - key: ACCOUNT.AVATAR
            name: { en: "Avatar", ru: "Аватар" }
            contentEncryption: AES
            contentTypes:
                - 'image/gif'
                - 'image/jpeg'
                - 'image/png'
                - 'image/tiff'
```
Entity type `dataEncryption` field could contain encryption algorithm (`AES`, `DES`) for data field and encryption should not be applied if algorithm not present (default logic).
`contentEncryption` field for the attachment has tha same logic as for the `dataEncryption`.

## Encryption/Decryption logic
* Entity data field encrypted when `dataEncryption` defined and save function called for the entity.
* If the field should be encrypted, then the Elasticsearch should be updated without data.
* Entity data field decrypted when `dataEncryption` not defined and save function called for the entity.
* Encryption/Decryption logic for the attachment content should be the same as for entity data field.
