### ISSUE TITLE
[Tuning] add the ability to configure columns in the entities list

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#78]
Add the ability to configure columns in the list of entities with such capabilities
1. Specify the number of columns
2. Specify the column output sequence
3. Edit column names
![image](https://user-images.githubusercontent.com/34374238/37515001-27999584-2912-11e8-8fb6-b80a04e41833.png)

**Comment by ishkurko** [comment]
You could use configuration via UI specification.
Example:
```
applications:
    config:
        entities:
            - typeKey: 'RESOURCE.CAR'
              fastSearch:
                - name: { "en": "In use" }
                  query: "stateKey:'IN-USE' AND locations.typeKey:RESOURCE.CAR.CURRENT-LOCATION AND locations.longitude:* AND locations.latitude:*"
              fields:
                - field: name
                  title: Name
                - field: typeKey
                  title: { "en": "Type" }
                - field: startDate
                  title: Start Date
                - field: stateKey
                  title: State
                - field: data.vin
                  title: VIN
```
will provide view:
<img width="1142" alt="screen shot 2018-04-05 at 19 10 14" src="https://user-images.githubusercontent.com/7899393/38377977-08ab8dfa-3905-11e8-9a97-70d36684aed7.png">
All parameters same as for the entities list widget:
https://github.com/xm-online/xm-online/wiki/How-to-manage-dashboards#widget-entities-list
