### ISSUE TITLE
UAA: Activation email subject

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#91]
Please add the possibility to customize (currently hardcoded) UAA Activation email subject in accordance with the tenant. 
Actual value: "XM^online account activation"

**Comment by sergeysenja1992** [comment]
Subject configure in tenant-config.yml

```
mailSettings:
# Mail template name
- templateName: customerAccountChanged
# Translation of subject
  subject:
  	en: Hello in system
	ru: Привет в системе
# Translation of from
  from:
	en: coolsystem@xm-online.com (Cool system)
	ru: coolsystem@xm-online.com (Классная система)
- templateName: passwordResetEmail
# You can specify translation key
# and translation must be in i18n-message.yml
  subject:
  	trKey: passwordResetEmailSubjectKey
  from:
	trKey: passwordResetEmailSubjectKey


translation in i18n-message.yml looks like
	...
passwordResetEmailSubjectKey:
	en: You reset password
	ru: Вы сбросили пароль
…

```
